namespace:
  name: junior-devops

replicaCount: 2

image:
  repository: 250205158357.dkr.ecr.us-east-1.amazonaws.com/junior-devops-api
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

container:
  port: 3000

env:
  port: "3000"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 20
