apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::250205158357:role/junior-devops-dev-eks-node-group-role
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::250205158357:role/github-actions-ecr-push-role
      username: github-actions
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-05T16:32:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "194973"
  uid: 47186ec2-e301-4b7e-bcd5-2b16d41e6f2d
