apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::250205158357:role/junior-devops-dev-eks-node-group-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::123456789012:role/github-actions-ecr-push-role
      username: github-actions
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-15T13:40:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "14158"
  uid: ea89fa50-0610-4963-b541-5c0df252dd0d
