apiVersion: v1
kind: Service
metadata:
  name: junior-devops-api
  namespace: junior-devops
  labels:
    app: junior-devops-api
spec:
  type: ClusterIP
  selector:
    app: junior-devops-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
